services:
  backend:
    image: tglevelsandeep/todo-backend:latest
    container_name: todo-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env                      # ← reads from .env on EC2, not hardcoded

  frontend:
    image: tglevelsandeep/todo-frontend:latest
    container_name: todo-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}   # ← picked from .env